### ISSUE TITLE
Getting 500 on all Requests

### ISSUE THREAD

**Issue by devtestingstuff** [vincent-queimado/express-prisma-ts-boilerplate#65]
All requests including the Swagger docs return 500 error and I am having trouble debugging what could be causing this.

<img width="865" alt="image" src="https://github.com/vincent-queimado/express-prisma-ts-boilerplate/assets/74066345/38189023-f8e1-49d8-b3e9-8ec576ec66c7">

<img width="1722" alt="image" src="https://github.com/vincent-queimado/express-prisma-ts-boilerplate/assets/74066345/fea77798-0aad-44c4-945d-92f1504f0df0">

**Comment by vincent-queimado** [comment]
Thanks for your feedback, I'm already checking. I believe the problem is in the "v1" api prefix that I recently changed when refactoring the routes. I'll come back with more information and fix if necessary.

**Comment by vincent-queimado** [comment]
@devtestingstuff, I updated the routes. Could you verify that access to the endpoints is working and that it complies with the documentation now.
